### PR TITLE
Add GitHub action CI (linux on Julia v1)

### PR DESCRIPTION
**Pull request by briochemc**
Don't merge. This is just trying to add a GitHub action CI.

### CODE REVIEW

**Comment by briochemc** [comment]
So I get that

```julia
β["cmip6-zarr-consolidated-stores.csv"]
```

is `nothing` which throws later in `IOBuffer`. 

This is all new stuff to me, so I'm slowly trying to figure out what's happening...

FYI, I just wanted to trigger a CI to see if that error was just on my side, and I thought I'd add a GitHub action one in the process.

**Comment by briochemc** [comment]
Raised in [Zarr.jl issue #53](https://github.com/meggart/Zarr.jl/issues/53) FWIW.

**Comment by gaelforget** [comment]
> Raised in [Zarr.jl issue #53](https://github.com/meggart/Zarr.jl/issues/53) FWIW.

The Zarr related error should be gone -- per https://github.com/gaelforget/ClimateModels.jl/pull/7

**Comment by gaelforget** [comment]
> Don't merge. This is just trying to add a GitHub action CI.

Sounds like a good idea. Easier than Travis CI?

Would probably need Julia 1.6 now though (due to Git.jl dependencies)

**Comment by briochemc** [comment]
> Sounds like a good idea. Easier than Travis CI?

Not sure, it does make it simpler in the sense that it's all within GitHub 🤷‍♂️

IIRC, the true motivation behind this PR was to see if the error was only on my local machine 😄

**Comment by gaelforget** [comment]
> > Sounds like a good idea. Easier than Travis CI?
> 
> Not sure, it does make it simpler in the sense that it's all within GitHub 🤷‍♂️
> 
> IIRC, the true motivation behind this PR was to see if the error was only on my local machine 😄

ok. For now I will keep this open, since the action approach might have advantages.  

BTW the CMIP6 example now runs on travis via Literate so should work for you too I would think

See https://gaelforget.github.io/ClimateModels.jl/dev/generated/CMIP6/

**Comment by gaelforget** [comment]
Closing this PR since now outdated -- see .github folder etc, I did this along the way

**Pull request closed without merging**
